---
title: "git_00"
author: "Gil Felix"
date: "Year 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
’Twas brillig, and the slithy toves  
Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
And the mome raths outgrabe.  

“Beware the Jabberwock, my son!  

## Second Verse
Two roads diverged in a yellow wood,  
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;  

## Third Verse
"The sun was shining on the sea,  
Shining with all his might:  

## Last Verse
Music to hear, why hear'st thou music sadly?  
Sweets with sweets war not, joy delights in joy.  
Why lov'st thou that which thou receiv'st not gladly,  
Or else receiv'st with pleasure thine annoy?  
If the true concord of well-tuned sounds,  
By unions married, do offend thine ear,  
They do but sweetly chide thee, who confounds  
In singleness the parts that thou shouldst bear.  
Mark how one string, sweet husband to another,  
Strikes each in each by mutual ordering,  
Resembling sire and child and happy mother  
Who all in one, one pleasing note do sing:  
Whose speechless song, being many, seeming one,  
Sings this to thee: 'Thou single wilt prove none.'  